server:
  port: 8216
spring:
  datasource:
    url: jdbc:sqlserver://yujin.database.windows.net:1433;database=yujing;user=yujin@yujin;password=12345678App;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

