server:
  port: 8216
spring:
  datasource:
    url: jdbc:mysql://yujinapp.cbwk0fuxtspa.ap-northeast-1.rds.amazonaws.com:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234-5678App




